name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.13.0
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  mongo_dart: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
